### PR TITLE
First draft working environments section

### PR DESCRIPTION
**Pull request by kathoef**
This turned out way too long. Please provide feedback on (1) topics and content, (2) the level of detail, and (3) overall style. In the meantime, I will probably work on the documentation section.

### CODE REVIEW

**Comment by willirath** [comment]
CI fails because of https://github.com/tectonic-typesetting/tectonic/issues/38 (which means tectonic won't support `minted`).

We should move away from tectonic, then.

**Comment by kathoef** [comment]
> CI fails because of [tectonic-typesetting/tectonic#38](https://github.com/tectonic-typesetting/tectonic/issues/38) (which means tectonic won't support `minted`).
> 
> We should move away from tectonic, then.

Thanks for looking this up... we should "reject" those last two commits then.

**Comment by willirath** [comment]
a4980ab fixes CI (but uses a relatively big docker image).

**Review by willirath — APPROVED** [review]

**Comment by kathoef** [comment]
To simplify restructuring, we'll merge this for now. The suggestions by Martin will be implemented at a later point.

**Pull request merged**
